### ISSUE TITLE
ts声明文件是不是得额外命令生成

### ISSUE THREAD

**Issue by MelodyLLL** [fallen-leaves-FE/vue3-component-library#1]
请问下 .d.ts文件怎样才可以和js文件绑定生成呢。类似antd那种库。另外在这个库里面也得使用额外命令生成吧。

**Comment by fallen-leaves-FE** [comment]
没有配置这个功能，可以研究一下rollup-plugin-dts这个插件

**Comment by fallen-leaves-FE** [comment]
升级为使用esbuild打包编译了，添加了vue-tsc工具

**Comment by MelodyLLL** [comment]
👍🏻，我学习一下


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月04日 14:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [fallen-leaves-FE/vue3-component-library] ts声明文件是不是得额外命令生成 (Issue #1) |

升级为使用esbuild打包编译了，添加了vue-tsc工具
